/// Compiles `java/dart/jni/DartInvocationHandler.java` and writes its bytes
/// into `lib/src/proxy_class.g.dart`.
///
/// Run after editing the Java source, and commit the result:
///
/// ```sh
/// dart run tool/gen_proxy_class.dart
/// ```
///
/// A JDK is needed here and nowhere else. Consumers get the class as Dart
/// source and load it with JNI `DefineClass`, so the package ships no jar and
/// asks nobody to run a build step.
library;

import 'dart:convert';
import 'dart:io';

void main(List<String> args) {
  final root = _packageRoot();
  final source = File('$root/java/dart/jni/DartInvocationHandler.java');
  if (!source.existsSync()) {
    _fail('missing ${source.path}');
  }

  final javac = _findJavac();
  stdout.writeln('javac: $javac');

  final work = Directory.systemTemp.createTempSync('java_interop_proxy_');
  try {
    // --release 11 pins the class file to major version 55. DefineClass rejects
    // a class file newer than the running VM with UnsupportedClassVersionError,
    // and only at runtime; 11 is the oldest release current JDKs still target,
    // and is below every JVM this package supports.
    final compile = Process.runSync(javac, [
      '--release',
      '11',
      '-Xlint:all',
      '-Werror',
      '-d',
      work.path,
      source.path,
    ]);
    if (compile.exitCode != 0) {
      stderr.write(compile.stdout);
      stderr.write(compile.stderr);
      _fail('javac failed');
    }

    final classFile = File('${work.path}/dart/jni/DartInvocationHandler.class');
    if (!classFile.existsSync()) {
      _fail('javac produced no ${classFile.path}');
    }

    final bytes = classFile.readAsBytesSync();
    // Bytes 6-7 of a class file are the major version, big-endian.
    final major = (bytes[6] << 8) | bytes[7];
    final version = Process.runSync(javac, ['-version']);
    final compiler = ('${version.stdout}${version.stderr}').trim();

    final encoded = base64.encode(bytes);
    final lines = <String>[];
    for (var i = 0; i < encoded.length; i += 68) {
      final end = i + 68 < encoded.length ? i + 68 : encoded.length;
      lines.add("  '${encoded.substring(i, end)}'");
    }

    final output = File('$root/lib/src/proxy_class.g.dart');
    output.writeAsStringSync('''
// GENERATED by tool/gen_proxy_class.dart — do not edit.
//
// The compiled bytes of java/dart/jni/DartInvocationHandler.java, which
// `JvmProxies.defineProxyClass` hands to JNI DefineClass. Read the Java source
// for what the class does; this file is only how it travels.
//
// class file version: $major (Java ${major - 44} bytecode), ${bytes.length} bytes
// compiled by: $compiler
library;

import 'dart:convert';
import 'dart:typed_data';

/// The binary name of the class in [proxyClassBytes], in JNI's slashed form.
const proxyClassName = 'dart/jni/DartInvocationHandler';

/// The compiled class file, decoded once on first use.
final Uint8List proxyClassBytes = base64.decode(_proxyClassBase64);

const _proxyClassBase64 =
${lines.join('\n')};
''');

    final format = Process.runSync('dart', ['format', output.path]);
    if (format.exitCode != 0) {
      stderr.write(format.stderr);
      _fail('dart format failed');
    }

    stdout.writeln(
      'wrote ${output.path} (${bytes.length} bytes, class version $major)',
    );
  } finally {
    work.deleteSync(recursive: true);
  }
}

/// The package root, walking up from this script.
String _packageRoot() {
  var directory = File.fromUri(Platform.script).parent;
  for (var i = 0; i < 6; i++) {
    if (File('${directory.path}/pubspec.yaml').existsSync()) {
      return directory.path;
    }
    final parent = directory.parent;
    if (parent.path == directory.path) break;
    directory = parent;
  }
  return Directory.current.path;
}

/// `javac`, from `JAVA_HOME` or the same places `test/java_home.sh` looks.
///
/// Kept in step with that script and with `searchLibjvm` in
/// `lib/src/java_home.dart`, so every entry point agrees on which JDK is in use.
String _findJavac() {
  final home = Platform.environment['JAVA_HOME'];
  if (home != null && home.isNotEmpty) {
    final javac = '$home/bin/javac';
    if (File(javac).existsSync()) return javac;
    _fail('JAVA_HOME=$home has no bin/javac (a JRE, not a JDK?)');
  }

  const candidates = [
    '/opt/homebrew/opt/openjdk/libexec/openjdk.jdk/Contents/Home',
    '/opt/homebrew/opt/openjdk@21/libexec/openjdk.jdk/Contents/Home',
    '/opt/homebrew/opt/openjdk@17/libexec/openjdk.jdk/Contents/Home',
    '/usr/local/opt/openjdk/libexec/openjdk.jdk/Contents/Home',
    '/usr/local/opt/openjdk@21/libexec/openjdk.jdk/Contents/Home',
    '/usr/local/opt/openjdk@17/libexec/openjdk.jdk/Contents/Home',
  ];
  for (final candidate in candidates) {
    if (File('$candidate/bin/javac').existsSync()) {
      return '$candidate/bin/javac';
    }
  }

  final lookup = File('/usr/libexec/java_home');
  if (lookup.existsSync()) {
    final result = Process.runSync(lookup.path, const []);
    if (result.exitCode == 0) {
      final home = (result.stdout as String).trim();
      if (File('$home/bin/javac').existsSync()) return '$home/bin/javac';
    }
  }

  _fail(
    'No JDK found. Set JAVA_HOME to a JDK (not a JRE), e.g.\n'
    r'  export JAVA_HOME="$(brew --prefix openjdk@21)'
    '/libexec/openjdk.jdk/Contents/Home"',
  );
}

Never _fail(String message) {
  stderr.writeln(message);
  exit(1);
}
